---
- name   : playbook 2 for NGINX
  hosts  : nginx
  become : yes
 
  tasks  :

  - name: Update repositories cache and install Nginx
    ansible.builtin.apt:
      name: nginx
      update_cache: yes

  - name: transfer config for NGINX
    copy: 
      src: /ansible/push/nginx/sites-available/default
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: '644'

  - name: restart nginx
    systemd:
      unit: nginx
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: install Filebeat for NGINX
    ansible.builtin.apt: 
      deb: /install/elk/filebeat_8.9.1_amd64.deb

  - name: transfer config for Filebeat
    copy: 
      src: /ansible/push/nginx/etc/filebeat/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: '600'

  - name: restart Filebeat
    systemd:
      unit: filebeat.service
      state: restarted
      enabled: yes
      daemon_reload: yes
...
