---
- name   : playbook 4 for MySQL source setup
  hosts  : mysqlsrs, mysqlrep
  become : yes
 
  tasks  :

  - name: copy MySQL repository
    copy:
      src   : /ansible/push/mysql/repository_add/etc/apt/sources.list.d/mysql.list
      dest  : /etc/apt/sources.list.d/mysql.list
      owner : root
      group : root
      mode  : '0644'
      backup: yes

  - name: copy MySQL repository keyring
    copy:
      src   : /ansible/push/mysql/repository_add/usr/share/keyrings/mysql-apt-config.gpg
      dest  : /usr/share/keyrings/mysql-apt-config.gpg
      owner : root
      group : root
      mode  : '0644'
      backup: yes

  - name: Execute command apt update
    shell: 
      cmd: "apt update"

  - name: Execute command install MySQL in noninteractive mode
    shell: 
      cmd: "export DEBIAN_FRONTEND=noninteractive && sudo -E apt install -y mysql-server"
...
