---
- name   : playbook 7 Prometheus and Grafana monitoring setup 
  hosts  : monitor
  become : yes
 
  tasks  :

  - name: Update repositories cache and install Prometheus
    ansible.builtin.apt:
      name: prometheus
      update_cache: yes

  - name: Install prometheus-nginx-exporter
    ansible.builtin.apt:
      name: prometheus-nginx-exporter
      update_cache: yes

  - name: transfer config for Prometheus
    copy: 
      src: /ansible/push/monitor/etc/prometheus/prometheus.yml
      dest: /etc/prometheus/prometheus.yml
      owner: root
      group: root
      mode: '644'

  - name: restart prometheus
    systemd:
      unit: prometheus
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: Execute command install Grafana
    shell: 
      cmd: cd /tmp && apt-get install -y adduser libfontconfig1 musl && wget https://dl.grafana.com/oss/release/grafana_10.4.2_amd64.deb && dpkg -i grafana_10.4.2_amd64.deb

  - name: start and enable Grafana
    systemd:
      unit: grafana-server.service
      state: restarted
      enabled: yes
      daemon_reload: yes
...
